- title: "Software As A Service"
  title_detail: "Systems for your growing business"
  slug: "services/hometurf"
  category: "Hometurf"
  color: "#0B2E39"
  images: "hometurf"
  cover: "./hometurf/ekko-puji-k7tyY8az6Bc-unsplash.jpg"
  image_credit: "Photo by Ekko Puji on Unsplash"  
  desc: "Color (American English), or colour (Commonwealth English), is the characteristic of human visual perception described through color categories, with names such as red, orange, yellow, green, blue, or purple. This perception of color derives from the stimulation of cone cells in the human eye by electromagnetic radiation in the visible spectrum. Color categories and physical specifications of color are associated with objects through the wavelength of the light that is reflected from them. This reflection is governed by the object's physical properties such as light absorption, emission spectra, etc."
  tags: services  
- title: "Consultancy"
  title_detail: "Helping your business grow"
  slug: "services/consultancy"
  category: "Consultancy"
  color: "#0B2E39"
  images: "consultancy"
  cover: "./consultancy/helloquence-5fNmWej4tAA-unsplash.jpg"
  image_credit: "Photo by Helloquence on Unsplash"  
  desc: "Monochrome photography is photography where each position on an image can record and show a different amount of light, but not a different hue. It includes all forms of black-and-white photography, which produce images containing tones of neutral grey ranging from black to white."
  tags: services  
- title: "Data Migration"
  title_detail: "Extract, Transform and Load"
  slug: "services/datamigration"
  category: "datamigration"
  color: "#0B2E39"
  images: "datamigration"
  cover: "./datamigration/patrick-lindenberg-1iVKwElWrPA-unsplash.jpg"
  image_credit: "Photo by Patrick Lindenberg on Unsplash"
  desc: "Extracting data for your business"
  tags: services  
  