- title: "Lawn Assessment"
  templateKey: service
  slug: "services/assessment"
  category: "Assessment"
  color: "#2B2C3E"
  images: "assessment"
  cover: "./assessment/lawnassessment.jpg"
  cover_alt: "Photo by Sarah Brown on Unsplash"  
  desc: "Once our Lawn Care Consultant has completed an assessment of your lawn, they will prerpare a quote for the appropriate course of treatments give you the best results."
  tags: services 
- title: "Lawn Renovations"
  templateKey: service
  slug: "services/renovation"
  category: "Lawn Renovation"
  color: "#2B2C3E"
  images: "renovation"
  cover: "./renovation/lawnsmatter_renovationcover.jpg"
  cover_alt: "Photo by Lawns Matter on client site"
  desc: "A lawn renovation can be the most efficient way to deliver the best results and delivers a much higher quality lawn than turfing can dweliver as the grass is thriving in your soil, rather than growing in a thin layer of soil that was delivered with the turf. "
  tags: services 
- title: "Feed and Weed"
  templateKey: service
  slug: "services/feedandweed"
  category: "Feed and Weed"
  color: "#2B2C3E"
  images: "feedandweed"
  cover: "./feedandweed/david-kaloczi-10xlYvD5yn4-unsplash.jpg"
  cover_alt: "Photo by David Kaloczi on Unsplash"
  desc: "It's a fact that lawns benefit from regular feeding. Without extra nutrients, the grass soon uses up plant food reserves in the soil and then turns pale and thin. "
  tags: services
- title: "Scarifying"
  templateKey: service
  slug: "services/scarifying"
  category: "scarifying"
  color: "#2B2C3E"
  images: "scarifying"
  cover: "./scarifying/scarifying-101.jpg"
  cover_alt: "Photo by Mukil Menon on Unsplash"
  desc: "Scarifying is extremely beneficial to the overall health of the lawn. It removes dead moss and built up thatch from the turf. Scarification times:  spring initial - summer light - autumn deep "
  tags: services
- title: "Aeration"
  templateKey: service
  slug: "services/aeration"
  category: "aeration"
  color: "#2B2C3E"
  images: "aeration"
  cover: "./aeration/aerator.jpg"
  cover_alt: "Photo by Mukil Menon on Unsplash"
  desc: "Aeration is to alleviate soil compaction which allows proper circulation of air, water and nutrients within the soil. Recommended times spring Mar-May and autumn Aug-Nov. Minimum at least once a year. "
  tags: services
- title: "Disease Control"
  templateKey: service
  slug: "services/diseasecontrol"
  category: "Disease Control"
  color: "#2B2C3E"
  images: "diseasecontrol"
  cover: "./diseasecontrol/disease.jpg"
  cover_alt: "Photo by from Lawns Matter's Facebook page"
  desc: "Our consultant will identify the appropriate course of treatment to address any disease affecting your lawn. "
  tags: services
- title: "Pest Control"
  templateKey: service
  slug: "services/pestcontrol"
  category: "Pest Control."
  color: "#2B2C3E"
  images: "pestcontrol"
  cover: "./pestcontrol/pestcontrol.jpg"
  cover_alt: "Photo by Tom Arrowsmith on Unsplash"
  desc: "If your lawn is infested with pests, our consultant will recommend a course of treatment to get rid of the infestation. "
  tags: services
  