- name: "About Us"  
  link: "/aboutus"
- name: "Our Service"
  link: "/service" 
- name: "Reviews"  
  link: "/reviews"
- name: "Any Questions?"  
  link: "/faq"
- name: "Portfolio"
  link: "/portfolio"
- name: "Contact Us"
  link: "/contactus"
