- name: "Our Service"
  link: "/service" 
- name: "Reviews"  
  link: "/reviews"
- name: "Any Questions?"  
  link: "/faq/"
- name: "Portfolio"
  link: "/page"
- name: "Instagram"  
  link: "/instagram"
- name: "Contact Us"
  link: "/contactus"
