- name: "Home"  
  link: "/"
- name: "Our Services"
  link: "/servicecatalog" 
- name: "Reviews"  
  link: "/reviews"
- name: "Any Questions?"  
  link: "/faqs"
- name: "Portfolio"
  link: "/page"
- name: "Instagram"  
  link: "/instagram"
- name: "Contact Us"
  link: "/contactus"
