- name: "Services"
  link: "/services" 
- name: "About"
  link: "/about"
- name: "Portfolio"
  link: "/portfolio"
- name: "Instagram"
  link: "/instagram"
- name: "Reviews"
  link: "/reviews"
- name: "Contact"
  link: "/contactus"